# Generated by Django 3.0.7 on 2021-01-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_registrationmodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationmodel',
            name='email',
        ),
        migrations.AddField(
            model_name='registrationmodel',
            name='contact',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
