# Generated by Django 3.0.7 on 2021-01-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20210114_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationmodel',
            name='contact',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
